// avatar-atlas.ts
// Generated by scripts/avatar-compose.mjs from design/avatar-kit. Do not edit.
// Canvas geometry and part names for the layered portraits in public/avatars.

export const ATLAS = {
  "width": 144,
  "height": 216,
  "chin": 138,
  "cx": 72,
  "hair": [
    "afro-short",
    "buzz",
    "curls-tight",
    "spiky",
    "side-swept",
    "blonde-curls",
    "bob",
    "dreads",
    "bald",
    "crop",
    "curls-short",
    "ponytail"
  ],
  "eyes": [
    "style-1",
    "style-2",
    "style-3",
    "style-4"
  ],
  "beards": [
    "beard-round",
    "mustache-handlebar",
    "mustache",
    "beard-full",
    "beard-open",
    "beard-long"
  ],
  "jerseys": [
    {
      "name": "pinstripe",
      "body": "#fefefe"
    },
    {
      "name": "white-red",
      "body": "#fefefe"
    },
    {
      "name": "grey",
      "body": "#ababb2"
    },
    {
      "name": "navy",
      "body": "#082e67"
    },
    {
      "name": "cream-gold",
      "body": "#fdfbf4"
    },
    {
      "name": "black-gold",
      "body": "#17191b"
    },
    {
      "name": "red",
      "body": "#d40720"
    },
    {
      "name": "green",
      "body": "#026138"
    },
    {
      "name": "purple",
      "body": "#5e0fc4"
    },
    {
      "name": "orange",
      "body": "#fe5f0b"
    },
    {
      "name": "light-blue",
      "body": "#53a6e4"
    },
    {
      "name": "catcher",
      "body": "#02265b"
    }
  ],
  "skins": [
    "#fed9bc",
    "#fd9e5c",
    "#e59360",
    "#b56d46",
    "#874f32",
    "#935738",
    "#905534",
    "#84492a",
    "#4e2a19",
    "#462617"
  ],
  "crown": {
    "afro-short": {
      "x": 74,
      "y": 50,
      "w": 71,
      "h": 40
    },
    "buzz": {
      "x": 73,
      "y": 49,
      "w": 71,
      "h": 40
    },
    "curls-tight": {
      "x": 75,
      "y": 47,
      "w": 73,
      "h": 41
    },
    "spiky": {
      "x": 72,
      "y": 47,
      "w": 72,
      "h": 42
    },
    "side-swept": {
      "x": 72,
      "y": 46,
      "w": 72,
      "h": 42
    },
    "blonde-curls": {
      "x": 73,
      "y": 52,
      "w": 83,
      "h": 53
    },
    "bob": {
      "x": 74,
      "y": 49,
      "w": 75,
      "h": 43
    },
    "dreads": {
      "x": 73,
      "y": 47,
      "w": 74,
      "h": 43
    },
    "bald": {
      "x": 74,
      "y": 45,
      "w": 73,
      "h": 42
    },
    "crop": {
      "x": 74,
      "y": 49,
      "w": 80,
      "h": 52
    },
    "curls-short": {
      "x": 72,
      "y": 51,
      "w": 77,
      "h": 52
    },
    "ponytail": {
      "x": 72,
      "y": 53,
      "w": 80,
      "h": 51
    }
  }
} as const;
